source :rubygems
gem "require_all"
gem "github-v3-api"
gem "capistrano"
gem "capistrano-ext"
gem "railsless-deploy"
gem "mongoid", "~> 2.3.3"
gem "bson_ext", "~> 1.4"
gem "httparty"
gem "pry"
gem "awesome_print"
