#!/usr/bin/env ruby
# Handy little console for WCNH systems development.

require 'rubygems'
require 'bundler'
Bundler.setup
require 'wirble'
require File.expand_path('../lib/wcnh.rb', __FILE__)
require 'irb'
require 'awesome_print'
Wirble.init
Wirble.colorize
IRB.start
